[book]
authors = ["yngtodd"]
multilingual = false
src = "src"
title = "DSE511"

[build]
build-dir = "book"
create-missing = false

[output.html]
theme = "gameboy"
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true

[output.html.playpen]
editable = false
copy-js = true
line-numbers = false
